### ISSUE TITLE
Original image management when forcing a different extension

### ISSUE THREAD

**Issue by jdecool** [novaway/NovawayFileManagementBundle#34]
I want to upload image and force a convertion to PNG.
My configuration : 

``` php
$filePath = array(
    'bundle.web' => '/',
    'picture' => '/uploads/{id}-{-imgformat-}.png',
);
```

But I also want to keep original file for future processing.

Actually, the bundle copy my original file and change extension but without any convertion. The result is that my file can't be read by some soft because of the invalid extension.

**Comment by skwi** [comment]
I just reassigned this issue to myself, @jdecool if you've already been working on it, please tell me

**Comment by jdecool** [comment]
You can :)

**Comment by jdecool** [comment]
@skwi Some news about this issue ?
