### ISSUE TITLE
[Refactoring] Persist management

### ISSUE THREAD

**Issue by jdecool** [novaway/NovawayFileManagementBundle#50]
Actually traits and interfaces use `save` and `delete` methods to manage entity persistance. This means that these methods are `abstract` and need to be implemented.

I propose to delete these method to use de default Doctrine EntityManager which can be passed as constructor argument.

**Comment by jdecool** [comment]
What do you think about ?
ping @skwi @delphiki @mickael-novaway

**Comment by mickael-novaway** [comment]
:+1:

**Comment by delphiki** [comment]
:+1:
