### ISSUE TITLE
Think about V4 roadmap

### ISSUE THREAD

**Issue by jdecool** [novaway/NovawayFileManagementBundle#59]
I'm thinking about a complete rewrite of the bundle from scratch. This issue is to discuss about which functionalities you want in this new version.

The objective of the rewrite is to refactor the code to have better architecture for future developments and an easier maintenance.

To this day, I planned to include all the current open issues plus :
- **Better implementation of strategy pattern**

The PR #37 which introduce a first version of strategy pattern have a code based on current architecture. And have a hard coded field to store some specific strategy information.

I think this code need to be clean.
- **Remove hard coded `UploadedFile` field in BaseEntity**

Linked to the previous point.

In a clean architecture, developer doesn't need to add non mapped field to implements some features.

If an extra field is needed, it need to be dynamically injected into the entity.
- **Annotation usage for some configurations**

It could be interesting to allow developer to configure entity with annotation in order to declare it in the config.yml.
- **Better tests**

Actually, there is some unit tests. They are not perfect, but they exist.

With the rewrite, we can make a better architecture for testing. We can also introduce some functional tests.
- **Allow file persistance in relations (#55)**

If an entity have a relation with an another, the saveWithFiles manage file only for the main entity. It could be very interesting to manager subrelation.
- **Allow different image manipulation provider**

The bundle is actually based on ImageWorkshop library. It will be great if we allow developer to choose what provider to use.
- **Allow to dynamic image resize filter**

Allow the bundle to store only original image (or only one version) but add filter to resize the file on the fly when the view is rendered.

<hr>

What do you think about this rewrite ? 

This issue is also about to discuss about what you want to include in the newer version.

**Comment by jdecool** [comment]
Rewrite begin => https://github.com/jdecool/NovawayFileManagementBundle/tree/4.0-DEV

**Comment by delphiki** [comment]
Note: an interesting discussion about file storage strategy: http://stackoverflow.com/questions/2648664/image-upload-storage-strategies

**Comment by skwi** [comment]
I've started to work on the image manipulation, with a more modulable system than the current one. It's not yet finished but if you guys can have a look at the architecture and tell me what you think or any suggestion to do it in a better way, please do so.

In a nutshell, I added an `ImageTransformerInterface` requiring the implementation of the method `transform` using an `ImageInterface`. The transformed `ImageInterface` will be returned so transformations can be chained. ImageTransformers can (and should) be atomic transformations or a  combination of smaller implementations of `ImageTransformerInterface`.
I also created a bridge and an adapter to use [Sybio's ImageWorkshop](https://github.com/Sybio/ImageWorkshop) as default image transformer, but transformations are not coupled to this library anymore.

You can see it there : https://github.com/skwi/NovawayFileManagementBundle/commit/6009e4c28fe1f512ff177ee27304ff482c078af5
